version: '3'
services:
  phoenix:
    build:
      context: .
      dockerfile: dev.Dockerfile
    depends_on:
      - postgres
    restart: always
    env_file:
      - .env
    environment:
      PG_USER: postgres
      PG_PASSWORD: postgres
      PG_DATABASE: notifier_dev
      PG_PORT: 5432
      PG_HOST: postgres
      PORT: 9000
    volumes:
      - ./config:/opt/app/config
      - ./lib:/opt/app/lib
      - ./priv:/opt/app/priv
      - ./_build:/opt/app/_build
      - ./.elixir_ls:/opt/app/.elixir_ls
      - ./deps:/opt/app/deps
    ports:
      - "9000:9000"
  postgres:
    image: postgres:9.6
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
    db_data:
