version: '3.2'
services:

  notifier:
    image: $FULL_IMAGE_NAME
    container_name: local-notifier
    ports:
    - "$PORT_VALUE:$PORT_VALUE"
    environment:
      - PORT=$PORT_VALUE
      - POOL_SIZE=$POOL_SIZE_VALUE
      - HOST=$HOST_VALUE
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - GUARDIAN_SECRET_KEY=$GUARDIAN_SECRET_KEY_VALUE
      - SECRET_KEY_BASE=$SECRET_KEY_BASE_VALUE
      - JWT_PUBLIC_KEY=$JWT_PUBLIC_KEY_VALUE
      - PG_HOST=db
      - PG_DATABASE=postgres
      - PG_USER=postgres
      - PGPASSWORD=postgres
    networks:
      sapien-local:
        ipv4_address: 172.24.0.5
    depends_on:
      - "db"
  db:
    image: postgres:10.5-alpine
    container_name: local-postgres
    ports:
    - "5432:5432"
    networks:
      sapien-local:
        ipv4_address: 172.24.0.6

networks:
  sapien-local:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.24.0.0/16
